server.port=8081
spring.application.name=AAS Discovery

# Enable Authorization
basyx.feature.authorization.enabled=true
basyx.feature.authorization.type=rbac
basyx.feature.authorization.jwtBearerTokenProvider=keycloak
basyx.feature.authorization.rbac.file=file:/application/rbac_rules.json

# Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/basyx

# Logging
logging.level.org.eclipse.basyx=DEBUG
logging.level.root=DEBUG