version: "3.7"

services:
  mongodb:
    image: mongo:5.0.10
    volumes:
      - mongodb-data-version-5.0.10:/data/db
    container_name: mongodb-aasreg-smreg-v3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"

  aas-registry-service:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name:  aas-registry-v3
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8050:8080
    depends_on:
      - mongodb
      - keycloak
    restart: always

  submodel-registry-service:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name:  submodel-registry-v3
    # pull_policy: never
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8051:8080
    depends_on:
      - mongodb
      - keycloak
    restart: always

  aas-environment-service:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name:  aas-environment-v3
    # pull_policy: never
    ports:
      - 8082:8081
    environment:
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      # SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/basyx
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry-service:8080 # <--- to register the AAS in the AAS registry
      BASYX_EXTERNALURL: http://localhost:8082 # <--- to create the connection from the registry to the environment
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://submodel-registry-service:8080 # <--- to register the submodels in the submodel registry
    volumes:
      - ./application.properties:/application/application.properties
      - ./config/rbac_rules.json:/application/rbac_rules.json
    depends_on:
      - mongodb
      - keycloak
    restart: always

  aas-web-ui:
      image: eclipsebasyx/aas-gui:v2-241114
      container_name: aas-web-ui
      ports:
          - "3000:3000"
      environment:
          AAS_REGISTRY_PATH: "http://localhost:8050"
          SUBMODEL_REGISTRY_PATH: "http://localhost:8051"
          AAS_DISCOVERY_PATH: "http://localhost:8083"
          AAS_REPO_PATH: "http://localhost:8082/shells"
          SUBMODEL_REPO_PATH: "http://localhost:8082/submodels"
          CD_REPO_PATH: "http://localhost:8082/concept-descriptions"
          # DASHBOARD_SERVICE_PATH: "<dashboard_service_path>" (optional; Time Series Data)
          PRIMARY_COLOR: "#3DB60F"
          LOGO_PATH: "Logo/murrelektronik_logo-green.svg"    # BASE_PATH: "<base_path>" (optional)
          # INFLUXDB_TOKEN: "<influxdb_token>" (optional; Time Series Data)
          KEYCLOAK_URL: "http://localhost:8080"  # Browser-accessible URL
          KEYCLOAK_REALM: "basyx"
          KEYCLOAK_CLIENT_ID: "aas-web-ui"  # New client ID for the web UI
      volumes:
       - /Users/juliusblezinger/Documents/Logo:/usr/src/app/dist/Logo
      depends_on:
        - aas-environment-service
        - keycloak

  # aas-discovery-service:
  #   image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
  #   container_name: aas-discovery-service
  #   volumes:
  #     - ./application.properties:/application/application.properties
  #   ports:
  #     - 8083:8081
  #   environment:
  #     BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
  #     BASYX_CORS_ALLOWED_ORIGINS: "*"
  #   depends_on:
  #     - mongodb
  #     - aas-environment-service
  #     - aas-registry-service
  #     - submodel-registry-service
  #     - keycloak
  #   restart: always

  aas-lookup-service:
    image: jbdesign23/aas-lookup-service:latest
    # image: aas-lookup-service:23-10-2024
    container_name: aas-lookup-service
    # pull_policy: never
    ports:
      - 8085:80
    # volumes:
    #   - /Users/juliusblezinger/Documents/Verwaltungsschalen:/app/Verwaltungsschalen
    depends_on:
      # - aas-discovery-service
      - aas-environment-service
      - aas-registry-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data 
    ports:
      - "8080:8080"
    command:
      - start-dev

volumes:
  mongodb-data-version-5.0.10:
    driver: local
  keycloak_data:
    driver: local
