version: "3.7"

services:
  mongodb:
    image: mongo:5.0.10
    volumes:
      - mongodb-data-version-5.0.10:/data/db
    container_name: mongodb-aasreg-smreg-v3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    #image: cr.siemens.com/aas/basyx-registry-server-java:1.2.0
    #platform: linux/amd64
    #volumes:
    #  - ./registry-config/context.properties:/usr/share/config/context.properties
    #  - ./registry-config/registry.properties:/usr/share/config/registry.properties
    #  - ./registry-config/mqtt.properties:/usr/share/config/mqtt.properties
    #   - ./common-config/FileBasedUserDBSettings.xml:/app/config/FileBasedUserDBSettings.xml
    #   - ./users:/app/users
    #ports:
    #  - 4999:4999
  aas-registry-service:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name:  aas-registry-v3
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8050:8080
    depends_on:
      - mongodb
    restart: always
    #image: cr.siemens.com/aas/basyx-registry-server-java:1.2.0
    #platform: linux/amd64
    #volumes:
    #  - ./registry-config/context.properties:/usr/share/config/context.properties
    #  - ./registry-config/registry.properties:/usr/share/config/registry.properties
    #  - ./registry-config/mqtt.properties:/usr/share/config/mqtt.properties
    #   - ./common-config/FileBasedUserDBSettings.xml:/app/config/FileBasedUserDBSettings.xml
    #   - ./users:/app/users
    #ports:
    #  - 4999:4999
  submodel-registry-service:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name:  submodel-registry-v3
    # pull_policy: never
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8051:8080
    depends_on:
      - mongodb
    restart: always
    #image: cr.siemens.com/aas/basyx-registry-server-java:1.2.0
    #platform: linux/amd64
    #volumes:
    #  - ./registry-config/context.properties:/usr/share/config/context.properties
    #  - ./registry-config/registry.properties:/usr/share/config/registry.properties
    #  - ./registry-config/mqtt.properties:/usr/share/config/mqtt.properties
    #   - ./common-config/FileBasedUserDBSettings.xml:/app/config/FileBasedUserDBSettings.xml
    #   - ./users:/app/users
    #ports:
    #  - 4999:4999
  aas-environment-service:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    volumes:
    - ./application.properties:/application/application.properties
    container_name:  aas-environment-v3
    # pull_policy: never
    ports:
      - 8082:8081
    environment:
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry-service:8080 # <--- to register the AAS in the AAS registry
      BASYX_EXTERNALURL: http://localhost:8082 # <--- to create the connection from the registry to the environment
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://submodel-registry-service:8080 # <--- to register the submodels in the submodel registry
    depends_on:
      - mongodb
    restart: always
    #image: cr.siemens.com/aas/basyx-registry-server-java:1.2.0
    #platform: linux/amd64
    #volumes:
    #  - ./registry-config/context.properties:/usr/share/config/context.properties
    #  - ./registry-config/registry.properties:/usr/share/config/registry.properties
    #  - ./registry-config/mqtt.properties:/usr/share/config/mqtt.properties
    #   - ./common-config/FileBasedUserDBSettings.xml:/app/config/FileBasedUserDBSettings.xml
    #   - ./users:/app/users
    #ports:
    #  - 4999:4999
  # mongo-express:
  #   image: mongo-express:1.0.0-alpha.4
  #   container_name: mongo-express-v3
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
  #   ports:
  #     - "0.0.0.0:8081:8081"
  #   depends_on:
  #     - mongodb

  aas-web-ui:
      image: eclipsebasyx/aas-gui:v2-241006
      container_name: aas-web-ui
      ports:
          - "3000:3000"
      environment:
          AAS_REGISTRY_PATH: "http://localhost:8050"
          SUBMODEL_REGISTRY_PATH: "http://localhost:8051"
          AAS_DISCOVERY_PATH: "http://localhost:8083"
          AAS_REPO_PATH: "http://localhost:8082/shells"
          SUBMODEL_REPO_PATH: "http://localhost:8082/submodels"
          CD_REPO_PATH: "http://localhost:8082/concept-descriptions"
          # DASHBOARD_SERVICE_PATH: "<dashboard_service_path>" (optional; Time Series Data)
          # PRIMARY_COLOR: "<primary_color>" (optional; Corporate Design)
          # LOGO_PATH: "<logo_path_in_container>" (optional; Corporate Design)
          # BASE_PATH: "<base_path>" (optional)
          # INFLUXDB_TOKEN: "<influxdb_token>" (optional; Time Series Data)
          # KEYCLOAK_URL: "<keycloak_url>" (optional; RBAC feature)
          # KEYCLOAK_REALM: "<keycloak_realm>" (optional; RBAC feature)
          # KEYCLOAK_CLIENT_ID: "<keycloak_client_id>" (optional; RBAC feature)
      depends_on:
        - aas-environment-service


  aas-discovery-service:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery-service
    volumes:
      - ./application.properties:/application/application.properties
    ports:
      - 8083:8081
    environment:
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      - mongodb
      - aas-environment-service
      - aas-registry-service
      - submodel-registry-service
    restart: always

  aas-lookup-service:
    # image: jbdesign23/aas-lookup-service:amd64-1.0
    image: aas-lookup-service
    container_name: aas-lookup-service
    pull_policy: never
    ports:
      - 8085:80
    volumes:
      - /Users/juliusblezinger/Documents/Verwaltungsschalen:/app/Verwaltungsschalen
    depends_on:
      - aas-discovery-service
      - aas-environment-service
      - aas-registry-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
   mongodb-data-version-5.0.10:
      driver: local
