# Use the official ASP.NET Core runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:ba7877fb3a171ad4326caf97d8b56304fe73e6e05da0992775804805f6f75451 AS build
WORKDIR /src
COPY ["AASLookupService.csproj", "."]
RUN dotnet restore "./AASLookupService.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "AASLookupService.csproj" -c Release -o /app/build

# Final stage / app image
FROM build AS publish
RUN dotnet publish "AASLookupService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=publish /app/publish/AASLookupService.xml .

ENTRYPOINT ["dotnet", "AASLookupService.dll"]
